version: "3.5"

services:
  source-db:
    image: postgres:10-alpine
    container_name: source-db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/source-db:/docker-entrypoint-initdb.d/
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  destination-db:
    image: postgres:10-alpine
    container_name: destination-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
networks:
  default:
    name: cdc-poc
