version: "3.5"

services:
  source-db:
    image: postgres:10-alpine
    container_name: source-db
    ports:
      - "5432:5432"
    command:
      [
        "postgres",
        "-c",
        "wal_level=logical",
        "-c",
        "max_wal_senders=2",
        "-c",
        "max_replication_slots=2",
      ]
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  destination-db:
    image: postgres:10-alpine
    container_name: destination-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
networks:
  default:
    name: cdc-poc
