apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: jdbc-sink-domain-event
  labels:
    app: cdc-poc
    # The strimzi.io/cluster label identifies the KafkaConnect instance
    # in which to create this connector. That KafkaConnect instance
    # must have the strimzi.io/use-connector-resources annotation
    # set to true.
    strimzi.io/cluster: cdc-poc
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    name: "jdbc-sink-domain-event"
    connector.class: "io.confluent.connect.jdbc.JdbcSinkConnector"
    tasks.max: "1"
    topics: "technology.cdc-poc.v1.domain_event"
    connection.url: "jdbc:postgresql://host.docker.internal:5433/postgres"
    connection.user: "postgres"
    connection.password: "postgres"
    transforms: "dropPrefix"
    transforms.dropPrefix.type: "org.apache.kafka.connect.transforms.RegexRouter"
    transforms.dropPrefix.regex: ".*\\..*\\..*\\.(.*)"
    transforms.dropPrefix.replacement: "$1"
    auto.create: "true"
    auto.evolve: "true"
    insert.mode: "upsert"
    delete.enabled: "true"
    pk.mode: "record_key"
    pk.fields: "id"
